---
- name: Run interfaces role
  hosts: frr
  gather_facts: true
  roles:
    - interfaces
  tags: interfaces

- name: Run frr role
  hosts: frr
  gather_facts: true
  roles:
    - frr
  tags: frr

- name: Run firewall role
  hosts: frr
  gather_facts: true
  roles:
    - firewall
  tags: firewall
  become: true
