- hosts: frr
  gather_facts: true
  roles:
    - interfaces
  tags: interfaces

- hosts: frr
  gather_facts: true
  roles:
    - frr
  tags: frr

- hosts: frr
  gather_facts: true
  roles:
    - firewall
  tags: firewall
  become: true
