---
- name: INTERFACES - Set wireguard config
  ansible.builtin.include_tasks:
    file: wireguard.yml
    apply:
      tags: wireguard
  loop: "{{ vrfs | dict2items }}"
  loop_control:
    loop_var: VRF
    label: "{{ VRF.key }}"
  tags: always
  notify: Ifreload

- name: INTERFACES - Set configuration in file
  ansible.builtin.template:
    src: "interfaces.j2"
    dest: /etc/network/interfaces
    mode: 0644
    # validate: ifup -a -s -i %s # validate fails with link-type wireguard
  become: true
  notify: Ifreload
