---
firewall:
  sets:
    - name: MGMT
      elements:
        - 169.254.33.0/24
    - name: CUSTOM_SET
      elements:
        - 1.1.1.1
        - 10.1.1.0/24
  filter:
    input:
      - comment: "Nice rule"
        statement: accept/drop/jump CHAIN/...  # default accept
        source:
          set: MGMT  # ip set name, only set or ip supported, not both
          ip: 10.1.1.1  # ip address
          interface: ens3  # in interface name
        destination:
          set:
          ip:
          port: 1337  # "{ 10, 22, https }" for multiple ports
          protocol: tcp
          interface:
        counter: true
    forward:
      -  # comment:
        # counter: true/false
        statement: accept
        source:
          set: MGMT
          # ip:
          # interface:
        destination:
          # set:
          # ip:
          port: "{ 22, 23, https }"  # "{ 10, 22, https }" for multiple ports
          protocol: tcp
          # interface:
