---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart node_exporter
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
    enabled: true
