---
- name: WIREGUARD - Create Private Configs
  ansible.builtin.template:
    src: wg-Private.conf.j2
    dest: ~/Documents/wireguardconfigs/wg-Private-{{ item.name }}.conf
    mode: 0644
  loop: "{{ (vrfs.remotesites.interfaces.wireguards
    | selectattr('name', 'eq', 'wgRoadwarrior') | list | first).wg.peers }}"
  delegate_to: localhost

- name: WIREGUARD - Create INET Configs
  ansible.builtin.template:
    src: wg-INET.conf.j2
    dest: ~/Documents/wireguardconfigs/wg-INET-{{ item.name }}.conf
    mode: 0644
  loop: "{{ (vrfs.remotesites.interfaces.wireguards
    | selectattr('name', 'eq', 'wgRoadwarrior') | list | first).wg.peers }}"
  delegate_to: localhost
