---
# https://github.com/CumulusNetworks/ifupdown2

- name: IFUPDOWN2 - Install and restart networking in one command for ansible
  ansible.builtin.shell: 'apt install ifupdown2 -y && systemctl restart networking'
  changed_when: true

- name: Disable systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: stopped
    enabled: false

- name: IFUPDOWN2 - Install optional packages
  ansible.builtin.apt:
    name:
      - bridge-utils
      - ethtool
    state: present
    update_cache: true

# should build from source but type wireguard is not working

# - name: IFUPDOWN2 - Get git repo
#   git:
#     repo: 'git://github.com/CumulusNetworks/ifupdown2'
#     dest: "/root/git"
#   tags: build
#
# - name: IFUPDOWN2 - build latest version
#   make:
#     chdir: "/root/git/ifupdown2"
#     target: "deb"
#   tags: build

# - name: IFUPDOWN2 - Install deb to host
#   apt:
#     deb: /root/ifupdown2/file.deb
