---
## COMMON TASKS MIGRATED TO github.com/33Fraise33/personal-ansible

- name: Import ifupdown2 Tasks
  ansible.builtin.import_tasks: ifupdown2.yml
  tags: ifupdown2

- name: Import Wireguard Tasks
  ansible.builtin.import_tasks: wireguard.yml
  tags: wireguard

- name: Import FRR Tasks
  ansible.builtin.import_tasks: frr.yml
  tags: frr

- name: Import node_exporter Tasks
  ansible.builtin.import_tasks: node_exporter.yml
  tags: node_exporter
