---
- name: HOSTNAME - Set to device
  ansible.builtin.hostname:
    name: '{{ inventory_hostname | replace("_", "-") }}'

- name: HOSTNAME - Set in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^(# *)?127.0.1.1	'
      line: '127.0.1.1	{{ inventory_hostname | replace("_", "-") }}'
    - regexp: '^(# *)?::1     '
      line: '::1     localhost ip6-localhost ip6-loopback {{ inventory_hostname | replace("_", "-") }}'

- name: Set timezone to UTC
  community.general.timezone:
    name: Etc/UTC

- name: Update apt packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install default packages
  ansible.builtin.apt:
    name:
      - systemd-timesyncd
      - vim
      - curl
      - git
      - htop
      - net-tools
      - fail2ban
      - traceroute
      - tcpdump
      - ncdu
      - mtr
      - python3-pip
      - nmap
    state: present

- name: Restart ntp daemon
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: true

- name: Set sysctl to enable ip forwarding
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
    - "net.ipv6.conf.default.forwarding"
    - "net.ipv6.conf.all.forwarding"
    - "net.ipv4.ip_forward"

- name: Import SSH Tasks
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh

- name: Import ifupdown2 Tasks
  ansible.builtin.import_tasks: ifupdown2.yml
  tags: ifupdown2

- name: Import Wireguard Tasks
  ansible.builtin.import_tasks: wireguard.yml
  tags: wireguard

- name: Import FRR Tasks
  ansible.builtin.import_tasks: frr.yml
  tags: frr

- name: Import node_exporter Tasks
  ansible.builtin.import_tasks: node_exporter.yml
  tags: node_exporter
