---
- name: SSH - Create user "{{ user.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: sudo
    append: true
    shell: /bin/bash
  loop: "{{ users }}"

- name: SSH - Set authorized keyfile for "{{ user.name }}"
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.pub_key }}"
  loop: "{{ users }}"

- name: SSH - Change daemon settings
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^(# *)?PermitRootLogin'
      line: 'PermitRootLogin no'
    - regexp: '^(# *)?UsePAM '
      line: 'UsePAM yes'
    - regexp: '^(# *)?PasswordAuthentication '
      line: 'PasswordAuthentication no'
    - regexp: '^(# *)?PermitEmptyPasswords '
      line: 'PermitEmptyPasswords no'
    - regexp: '^(# *)?ChallengeResponseAuthentication '
      line: 'ChallengeResponseAuthentication no'
    - regexp: '^(# *)?Port '
      line: 'Port 1830'
  notify:
    - Restart sshd

- name: SSH - Remove debian user
  ansible.builtin.user:
    name: "debian"
    state: absent
  when: ansible_user|default() != "debian"
