---
all:
  children:
    frr:
      children:
        beokpdco:
        defraifg:
    beokpdco:
      hosts:
        beokpdcort01:
          ansible_host: "2001:678:1080::2"
    defraifg:
      hosts:
        defraifgrt01:
          ansible_host: "2001:678:1080::1"
