---
- name: SETUP - install sudo package
  ansible.builtin.apt:
    name:
      - sudo
    state: present
  become_method: su

- name: SETUP - Allow sudo user group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become_method: su

- name: SETUP - temporarily add debian to the sudo group
  ansible.builtin.user:
    name: debian
    groups: sudo
    append: true
  become_method: su

- name: SETUP - reset connection so sudo permission is recognized
  ansible.builtin.meta: reset_connection

- name: SETUP - Generate random root password
  ansible.builtin.set_fact:
    setup_new_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,.,_,! length=15') }}"

- name: SETUP - Add password to file
  ansible.builtin.lineinfile:
    path: "~/root_password"
    line: "{{ lookup('pipe', 'date -u +%FT%TZ') }};{{ inventory_hostname }};{{ setup_new_password }}"
    owner: root
    group: root
    mode: 0644
    create: true
  delegate_to: localhost

- name: SETUP - change root user password
  ansible.builtin.user:
    name: "root"
    password: "{{ setup_new_password | password_hash('sha512', 'mysecretsalt') }}"

- name: SETUP - Set ssh port to 1830
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(# *)?Port '
    line: 'Port 1830'

- name: SETUP - reload sshd
  ansible.builtin.systemd:
    name: sshd
    state: reloaded
    enabled: true
