---
vrfs:
  default:
    interfaces:
      loopback:
        ipv6:
          addresses:
            - 2a12:4946:4001::1/64
      physicals:
        - name: "ens18"
          description: "IFOG PEERING"
          mtu: 1500
          ipv4:
            addresses:
              - 193.148.249.106/24
            gateway: 193.148.249.1
          ipv6:
            addresses:
              - 2a0c:9a40:1::916/48
    routing:
      bgp:
        as: 211184
        router_id: 193.148.249.106
        imports:
          v6:
            vrfs:
              - remotesites
          v4:
            vrfs:
              - remotesites
        networks:
          v6:
            - 2a12:4946:4000::/48
            - 2a12:4946:4001::/48
        redistribute:
          - static
        neighbor_groups:
          - peer: default
            soft_reconfiguration_inbound: true
            local_role: customer
            activate:
              - v6
            timers:
              keepalive: 20
              hold: 60
            route_maps:
              - direction: in
                name: rm-DEFAULT_ONLY_PUBLIC
              - direction: out
                name: rm-AS211184-48
        neighbors:
          - neighbor_group: default
            peer: 2a0c:9a40:1::1
            as: 34927
            description: "IFOG PEERING"
      static:
        - destination: ::/0
          gateway: 2a0c:9a40:1::1
        - destination: 192.0.0.1/32
          type: blackhole
  remotesites:
    interfaces:
      loopback:
        ipv6:
          addresses:
            - 2a12:4946:4001:10::1/64
        ipv4:
          addresses:
            - 10.10.33.1/32
      wireguards:
        - name: wgAsgard
          description: "WG Transit to Asgard"
          mtu: 1500
          wg:
            port: 51820
            keepalive: 25
            private_key: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              37393265653834313137636263613566613734663730666236363437663865386535316638343436
              3938383464376465313962663735653234356434643535620a333562333261306433313266326164
              39333633633763656634646635366430376262306664333536393130373930646330353965303235
              3838376330323832330a646535653735616438343036363962653735383663643133613430326366
              61343665323665616533383866346362373534393338633931383066373366326337393364633063
              3537303362626231336566303866393565393366313630353139
            public_key: AT8EI+D8hCr6pn5jY7FeEeDTLRbr7vEPSPWYpE7fT0U=
            peers:
              - name: ASGARD
                id: 10
                public_key: YjNlhACGkOWj62eAn0qFY+su3uaGo9w8rJYpLyDZ/DY=
                private_key: "notneeded"
          ipv6:
            addresses:
              - 2a12:4946:4001:34::1:1/112
              - fe80:34::1:1/64
    routing:
      bgp:
        graceful_restart: false
        as: 211184
        router_id: 10.10.33.1
        imports:
          v6:
            route_map: rm-DEFUALT_TO_REMOTE
            vrfs:
              - default
          v4:
            vrfs:
              - default
        redistribute:
          - connected
        neighbor_groups:
          - peer: remotesites
            soft_reconfiguration_inbound: true
            timers:
              keepalive: 20
              hold: 60
            route_maps:
              - direction: in
                name: rm-REMOTE_SITES-in
              - direction: out
                name: rm-REMOTE_SITES-out
        neighbors:
          - neighbor_group: remotesites
            peer: 2a12:4946:4001:34::1:2
            activate:
              - v6
            as: 65501
            description: "ASGARDv6"
            route_maps:
              - direction: in
                name: rm-REMOTE_SITES-in
              - direction: out
                name: rm-ASGARD-out

route_filtering:
  prefix_lists:
    - name: pl-default-public
      lists:
        - prefix: 0.0.0.0/0
          policy: permit
          le: 24
          ge: 0
        - prefix: ::/0
          policy: permit
          le: 48
          ge: 0
    - name: pl-default
      lists:
        - prefix: 0.0.0.0/0
          policy: permit
        - prefix: ::/0
          policy: permit
    - name: pl-default-bogons
      lists:
        - prefix: 0.0.0.0/0
          policy: permit
          ge: 25
        - prefix: ::/0
          policy: permit
          ge: 49
    - name: pl-AS211184-48
      lists:
        - prefix: 2a12:4946:4000::/44
          le: 48
          policy: permit
    - name: pl-AS211184
      lists:
        - prefix: 2a12:4946:4000::/44
          policy: permit
          ge: 44
    - name: pl-RFC1918
      lists:
        - prefix: 10.0.0.0/8
          policy: permit
          ge: 8
        - prefix: 172.16.0.0/12
          policy: permit
          ge: 12
        - prefix: 192.168.0.0/16
          policy: permit
          ge: 16
    - name: pl-MGMT
      lists:
        - prefix: 172.16.33.0/24
          policy: permit
        - prefix: 10.33.0.0/24
          policy: permit
        - prefix: 10.10.33.1/32
          policy: permit
        - prefix: 10.10.35.0/24
          policy: permit
  route_maps:
    - name: rm-DEFAULT_ONLY_PUBLIC
      maps:
        - match:
            v4_prefix_list: pl-default-public
          policy: permit
        - match:
            v6_prefix_list: pl-default-public
          policy: permit
    - name: rm-fullbogons-in
      maps:
        - match:
            v6_prefix_list: pl-default-bogons
          action:
            on_match: next
          policy: permit
        - match:
            community: bogons
          action:
            set:
              next_hop: 192.0.0.1
          policy: permit
    - name: rm-DEFUALT_TO_REMOTE
      maps:
        - match:
            v6_prefix_list: pl-AS211184
          policy: permit
        - match:
            v6_prefix_list: pl-default
          policy: permit
    - name: rm-AS211184-48
      maps:
        - match:
            v6_prefix_list: pl-AS211184-48
          policy: permit
    - name: rm-AS211184
      maps:
        - match:
            v6_prefix_list: pl-AS211184
          policy: permit
    - name: rm-REMOTE_SITES-in
      maps:
        - match:
            v6_prefix_list: pl-AS211184
          policy: permit
        - match:
            v4_prefix_list: pl-RFC1918
          policy: permit
    - name: rm-REMOTE_SITES-out
      maps:
        - match:
            v6_prefix_list: pl-AS211184
          policy: permit
        - match:
            v4_prefix_list: pl-MGMT
          policy: permit
    - name: rm-ASGARD-out
      maps:
        - match:
            v6_prefix_list: pl-AS211184
          policy: permit
        - match:
            v4_prefix_list: pl-RFC1918
          policy: permit
        - match:
            v6_prefix_list: pl-default
          policy: permit
    - name: rm-default
      maps:
        - match:
            v6_prefix_list: pl-default
          policy: permit
        - match:
            v4_prefix_list: pl-default
          policy: permit
    - name: rm-deny
      maps:
        - policy: deny
  communities:
    - name: bogons
      content:
        - community: "64496:0"

firewall:
  sets:
    - name: RFC1918
      type: ipv4
      elements:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    - name: MGMT
      type: ipv4
      elements:
        - 10.33.0.0/24  # Docker Network
        - 10.10.35.0/24  # Wireguard Roadwarrior
    - name: AS211184
      type: ipv6
      elements:
        - 2a12:4946:4000::/44
    - name: BGP_CYMRU
      type: ipv6
      elements:
        - 2604:8800:50:81:216:31:3:81  # Cymru Fullbogons #1
        - 2604:8800:60:81:216:31:7:81  # Cymru Fullbogons #2
    - name: BGP_PEERS_v6
      type: ipv6
      elements:
        - 2a0c:9a40:1::1  # IFOG
        - 2001:7f8:33::a103:1142:1  # kleyrex rs1
        - 2001:7f8:33::a103:1142:2  # kleyrex rs2
        - 2001:7f8:33::a103:1142:3  # kleyrex rs3
        - 2001:7f8:f2:e1::babe:1  # locix rs1
        - 2001:7f8:f2:e1::dead:1  # locix rs2
        - 2001:7f8:f2:e1::be5a  # locix rs3
        - 2001:7f8:ca:1::111  # fogixp rs1
        - 2001:7f8:ca:1::77  # bubacarr sowe
        - 2a12:4946:4001:34::1:2  # ASGARD
        - 2001:7f8:f2:e1::6939:1  # HE Locix
    - name: BGP_PEERS_v4
      type: ipv4
      elements:
        - 10.10.34.2  # ASGARD
        - 10.10.34.18  # UNITIX_KIT01
        - 10.10.34.22  # UNITIX_KIT02
        - 10.10.34.6  # MOM
        - 10.10.34.14  # DAD
  filter:
    input:
      - comment: "Allow SSH"
        destination:
          port: 1830
          protocol: tcp
        counter: true
      - comment: "Allow node_exporter from MGMT"
        source:
          set: MGMT
        destination:
          port: 9100
          protocol: tcp
        counter: true
      - comment: "Allow frr_expoter from MGMT"
        source:
          set: MGMT
        destination:
          port: 9342
          protocol: tcp
        counter: true
      - comment: "Allow BGP from PEERS_v4"
        source:
          set: BGP_PEERS_v4
        destination:
          port: 179
          protocol: tcp
        counter: true
      - comment: "Allow BGP from PEERS_v6"
        type: ip6
        source:
          set: BGP_PEERS_v6
        destination:
          port: 179
          protocol: tcp
        counter: true
      - comment: "Allow BGP from CYMRU"
        type: ip6
        source:
          set: BGP_CYMRU
        destination:
          port: 179
          protocol: tcp
        counter: true
      - comment: "Allow Wireguard edge sites"
        destination:
          port: 51820-51830
          protocol: udp
        counter: true
      - comment: "Allow Wireguard Roadwarrior"
        destination:
          port: 2034
          protocol: udp
        counter: true
    forward:
      - comment: "Allow from MGMT"  # needed for monitoring towards edge sites
        source:
          set: MGMT
        counter: true
      - comment: "Allow AS211184 out of ens interfaces"
        type: ip6
        source:
          set: AS211184
        destination:
          interface: "ens*"
        counter: true
      - comment: "Allow to AS211184"
        type: ip6
        destination:
          set: AS211184
        counter: true
  nat:
    srcnat:
      - statement: snat to 193.148.249.106
        source:
          set: MGMT
        destination:
          negate: true
          set: RFC1918

# dstnat:
