- name: reload frr
  systemd:
    name: frr
    state: reloaded
    enabled: true
  become: true

- name: restart frr_exporter
  systemd:
    daemon_reload: true
    name: frr_exporter
    state: restarted
    enabled: yes
  become: true
