---
- name: Reload frr
  ansible.builtin.systemd:
    name: frr
    state: reloaded
    enabled: true
  become: true

- name: Restart frr_exporter
  ansible.builtin.systemd:
    daemon_reload: true
    name: frr_exporter
    state: restarted
    enabled: true
  become: true
